### ISSUE TITLE
Update DynamoDB API from 20111205 to 20120810

### ISSUE THREAD

**Issue by wesleybits** [greghendershott/aws#57]
This should open up the ability to test Dynamo interfacing programs against a local in-memory instance of Dynamo, and being up-to-date is generally a good thing.

[Getting DynamoDBLocal](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)
[New API Basics](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.LowLevelAPI.html)
[New API Operations & Request Schema](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Operations_Amazon_DynamoDB.html)

From what I understand so far, this doesn't seem to be too hard. Mind if I put together a PR for it? I'll need guidance with how you want me to update the unit tests.

**Comment by greghendershott** [comment]
Basically I think this sounds good, provided it doesn't break anything. :)

Dynamo isn't a part of AWS I've ever actually used for real. I'm not sure how many users of this Racket package are actively using Dynamo, either.  Is the new API backward compatible? If so, great. Otherwise,  let's discuss how to avoid breaking existing users.

I'm not sure how if at all the unit tests should be updated. What do you think?

**Comment by wesleybits** [comment]
The new API doesn't appear backwards compatible, but it seems that AWS is still hosting the older API with deprecation warnings attached. It's got a richer (more busy) JSON schema to it. It supports new types, like lists and maps, and added support for secondary indexes and table projections.

To keep things sane-ish, we could probably bin both implementations into separate modules, or units, and determine which one to use depending on the value of some dynamo-version parameter that defaults to what's implemented already, like "20111205". We could also `defraw` everything, since the JSON schema for either isn't all that complicated, and it makes the management of the proposed dynamo version param much easier.

I haven't actually used DynamoDB all that much, either, but wound up writing an ETL system in Racket for some reason.

**Comment by greghendershott** [comment]
I just pushed a commit for this. Could you take a look and let me know what you think about the approach?

I haven't done anything to update the tests. Or even tried using this. The commit is to get your feedback.

**Comment by wesleybits** [comment]
This look a lot like what I did to try to get it working Friday, except I only provided raw. I'll give it a shot this afternoon.

**Comment by wesleybits** [comment]
OK, it looks like the contract for `dynamo-request` was reversed in the code. After fixing that, it seems it works a real treat. Do you mind if I commit the correction?

**Comment by greghendershott** [comment]
Derp. Thanks for noticing and for offering to fix.

But also:

- Running the tests for real, now: I noticed a problem with the backward-compatibility wrapper macros.

- Re-reading my doc changes, I want to edit the prose.

So, I think I need/want to make another commit, anyway -- so I may as well correct the contract while I'm at it.

**Comment by wesleybits** [comment]
Alrighty. I'll keep tabs on this ticket and give it another run-through when you're ready.

**Comment by greghendershott** [comment]
I just pushed some more commits on the [`issue-57-dynamo-api` branch](https://github.com/greghendershott/aws/commits/issue-57-dynamo-api).

You're welcome to try if you have time in the next day or two. (Otherwise if I don't hear back, I'll go ahead and merge.)

Note: I'll squash before merging to `master`. I did them as little commits in case you were curious what I was doing.

**Comment by wesleybits** [comment]
:+1: 

It works fine for me, much thanks!
